# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7bdaf6009074733ec686bc36fef86ab2189227424062166a781fdc0d79610fb1781fce4ca8dd3ca6204b8b7dca874e64b61262e79ee576f8a3b0b814bf02aa7

test:
  secret_key_base: b7589af1ba30799c036ffe9f821697042962c0962a449a6d60ba00798bbcc1dd88c26628e42d119b18b67f09d433076763516d52e563cd0b46e59ff779f05c10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
